channels:
  - conda-forge
dependencies:
  - black
  - bokeh
  - boto3
  - bottleneck
  - cenpy
  - clustergram
  - contextily
  - cubo
  - cython
  - dask
  - dask-geopandas
  - datashader
  - flake8
  - geoalchemy2
  - geocube
  - geopandas>=1
  - geopy
  - gpxpy
  - gstools
  - h3-py
  - hdbscan
  - hilbertcurve
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyter_bokeh
  - jupyter-book
  - jupyter-collaboration
  - jupyter-resource-usage
  - jupyterlab>=4.0
  - jupytext
  - legendgram
  - libgdal-arrow-parquet
  - lonboard
  - lxml
  - matplotlib
  - matplotlib-scalebar
  - momepy
  - movingpandas
  - netCDF4
  - networkx
  - numba
  - openpyxl
  - osmnx
  - palettable
  - pandana
  - polyline
  - pooch
  - protobuf
  - psycopg2
  - pyarrow
  - pyogrio
  - pyppeteer
  - pysal
  - pystac-client
  - pytest
  - python-duckdb
  - rasterio
  - rasterstats
  - rio-cogeo
  - rioxarray
  - ruff
  - scikit-learn
  - scikit-mobility
  - seaborn
  - spatialpandas
  - sqlalchemy
  - statsmodels
  - tabulate
  - topojson
  - urbanaccess
  - xarray_leaflet
  - xarray-spatial
  - xlrd
  - xlsxwriter
  - xvec
  - python-build
  - jupyter-server-proxy
  - code-server >=3.2
  - pip
  - pip:
    - jupyterlab-geojson
    - jupyterlab_myst
    - jupyter-vscode-proxy
    - matplotlib-scalebar
    - polars
    - pymorton
    - pytest-cov
    - pytest-tornasync
    - simplification
    - urbangrammar-graphics
    - watermark
    - geoarrow-pyarrow
    - geoarrow-pandas
    - geoplanar
